ACTIVE_SHALLOW:
  PGV: Br_13
  PGA: Br_13
  pSA: Br_13
  CAV: CB_12
  AI: CB_12
  Ds575: AS_16
  Ds595: AS_16
  Ds2080: AS_16
VOLCANIC:
  PGV: Br_13
  PGA: Br_13
  pSA: Br_13
SUBDUCTION_SLAB:
  PGA: ZA_06
  pSA: ZA_06
SUBDUCTION_INTERFACE:
  PGA: ZA_06
  pSA: ZA_06
