pSA:
        ACTIVE_SHALLOW:
                A_22: 0.28
                S_22: 0.28
                ASK_14: 0.066
                CY_14: 0.066
                CB_14: 0.066
                BSSA_14: 0.066
                Br_13: 0.066
        VOLCANIC:
                A_22: 0.28
                S_22: 0.28
                ASK_14: 0.066
                CY_14: 0.066
                CB_14: 0.066
                BSSA_14: 0.066
                Br_13: 0.066
        SUBDUCTION_INTERFACE:
                A_22: 0.27
                AG_20: 0.25
                K_20: 0.24
                P_21: 0.24
        SUBDUCTION_SLAB:
                A_22: 0.28
                AG_20: 0.25
                K_20: 0.24
                P_21: 0.23
