pSA:
        ACTIVE_SHALLOW:
                A_22: 
                        LOWER: 0.084    # 0.28 * 0.3
                        CENTRAL: 0.112  # 0.28 * 0.4
                        UPPER: 0.084    # 0.28 * 0.3
                S_22: 
                        LOWER: 0.117    # 0.39 * 0.3
                        CENTRAL: 0.156  # 0.39 * 0.4
                        UPPER: 0.117    # 0.39 * 0.3
                ASK_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                CY_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                CB_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                BSSA_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                Br_13:  
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
        VOLCANIC:
                A_22: 
                        LOWER: 0.084    # 0.28 * 0.3
                        CENTRAL: 0.112  # 0.28 * 0.4
                        UPPER: 0.084    # 0.28 * 0.3
                S_22: 
                        LOWER: 0.117    # 0.39 * 0.3
                        CENTRAL: 0.156  # 0.39 * 0.4
                        UPPER: 0.117    # 0.39 * 0.3
                ASK_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                CY_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                CB_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                BSSA_14:
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
                Br_13:  
                        LOWER: 0.0198   # 0.33 * 0.2 * 0.3
                        CENTRAL: 0.0264 # 0.33 * 0.2 * 0.4
                        UPPER: 0.0198   # 0.33 * 0.2 * 0.3
        SUBDUCTION_INTERFACE:
                A_22: 
                        LOWER: 0.081    # 0.27 * 0.3
                        CENTRAL: 0.108  # 0.27 * 0.4
                        UPPER: 0.081    # 0.27 * 0.3
                AG_20: 
                        LOWER: 0.075    # 0.25 * 0.3
                        CENTRAL: 0.1    # 0.25 * 0.4
                        UPPER: 0.075    # 0.25 * 0.3
                K_20: 
                        LOWER: 0.072    # 0.24 * 0.3
                        CENTRAL: 0.096  # 0.24 * 0.4
                        UPPER: 0.072    # 0.24 * 0.3
                P_21: 
                        LOWER: 0.072    # 0.24 * 0.3
                        CENTRAL: 0.096  # 0.24 * 0.4
                        UPPER: 0.072    # 0.24 * 0.3
        SUBDUCTION_SLAB:
                A_22: 
                        LOWER: 0.084    # 0.28 * 0.3
                        CENTRAL: 0.112  # 0.28 * 0.4
                        UPPER: 0.084    # 0.28 * 0.3
                AG_20: 
                        LOWER: 0.075    # 0.25 * 0.3
                        CENTRAL: 0.1    # 0.25 * 0.4
                        UPPER: 0.075    # 0.25 * 0.3
                K_20: 
                        LOWER: 0.072    # 0.24 * 0.3
                        CENTRAL: 0.096  # 0.24 * 0.4
                        UPPER: 0.072    # 0.24 * 0.3
                P_21: 
                        LOWER: 0.069    # 0.23 * 0.3
                        CENTRAL: 0.092  # 0.23 * 0.4
                        UPPER: 0.069    # 0.23 * 0.3
