#select a empirical model for the tect-type and intensity measure
# current valid options are:
# Br_10 -- Bradley 2010
# ZA_06 -- Zhao 2006
# CB_12 -- Campbell  Bozorgina 2012
# CB_10 -- Campbell  Bozorgina 2010
# AS_16 -- Afshari Stewart 2016
# ASK_14 -- Abrahamson Silva Kamai 2014
# BCH_16 -- BC Hydro 2016 Subduction
# BSSA_14 -- Boore Stewart Seyhan Atkinson 2014
# CB_14 -- Campbell Bozorgina 2014 NGA
# CY_14 -- Chiou Youngso2014 NGA
# SB_13 -- Shahi Baker 2013
# BB_13 -- Burks Baker 2013
# A_18 -- Abrahamson 2018 Subduction

### OpenQuake Models
# P_20_SI -- Parker 2020 Subduction Interface
# P_20_SS -- Parker 2020 Subduction Slab
# HA_20_CR -- HAssaniAtkinson 2020 Shallow Crustal
# HA_20_SI -- HAssaniAtkinson 2020 Suduction Interface
# HA_20_SS -- HAssaniAtkinson 2020 Suduction Slab

# G_17 -- Gulerce et al 2017 Vertical
# BC_16 -- BorzorginaCampbell 2016 Vertical
# S_16 -- Stewart et al 2016 Vertical

# Options for each model are listed to the right
ACTIVE_SHALLOW:
  PGV:
    rotd50:
      - META
    geom:
      - CY_14
  PGA:
    rotd50:
      - META
    geom:
      - Br_10
  pSA:
    rotd50:
      - META
    geom:
      - Br_10
  CAV:
    rotd50:
      - CB_10
    geom:
      - CB_10
  AI:
    geom:
      - CB_12
  Ds575:
    rotd50:
      - AS_16
    geom:
      - AS_16
  Ds595:
    rotd50:
      - AS_16
    geom:
      - AS_16
  Ds2080:
    geom:
      - AS_16
  IESDR:
    geom:
      - BB_13

VOLCANIC:
  PGV:
    geom:
      - Br_10
  PGA:
    geom:
      - Br_10
  pSA:
    geom:
      - Br_10
    rotd100_50:
      - SB_13
  CAV:
    geom:
      - CB_10 # These are only for shallow crustal in lieu of a more appropriate model
  AI:
    geom:
      - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  Ds575:
    geom:
      - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  Ds595:
    geom:
      - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  IESDR:
    geom:
      - BB_13
SUBDUCTION_SLAB:
  PGV:
    rotd50:
      - META
  PGA:
    rotd50:
      - META
  pSA:
    rotd50:
      - META
    geom:
      - A_18 # ZA06 or BCH16
    rotd100_50:
      - SB_13
  CAV:
    geom:
      - CB_10 # These are only for shallow crustal in lieu of a more appropriate model
  AI:
    geom:
      - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  Ds575:
    geom:
      - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  Ds595:
    geom:
      - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  IESDR:
    geom:
      - BB_13
SUBDUCTION_INTERFACE:
  PGV:
    rotd50:
      - META # These are only for shallow crustal in lieu of a more appropriate model
  PGA:
    rotd50:
      - META # ZA06 or BCH16
  pSA:
    rotd50:
      - META
    geom:
      - A_18 # ZA06 or BCH16
    rotd100_50:
      - SB_13
  CAV:
    geom:
      - CB_10 # These are only for shallow crustal in lieu of a more appropriate model
  AI:
    geom:
      - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  Ds575:
    geom:
      - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  Ds595:
    geom:
      - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  IESDR:
    geom:
      - BB_13
