#select a empirical model for the tect-type and intensity measure
# current valid options are:
# Br_10 -- Bradley 2013
# ZA_06 -- Zhao 2006
# CB_12 -- Campbell  Bozorgina 2012
# AS_16 -- Afshari Stewart 2016
# ASK_14 -- Abrahamson Silva Kamai 2014
# BC_16 -- BC Hydro 2016
# BSSA_14 -- Boore Stewart Seyhan Atkinson 2014
# CB_14 -- Campbell Bozorgina 2014 NGA
# CY_14 -- Chiou Youngso2014 NGA



# Options for each model are listed to the right
ACTIVE_SHALLOW:
  PGV:
    - Br_10
  PGA:
    - Br_10 # ZA_06 or Br_10
  pSA:
    - Br_10 # ZA_06 or Br_10
  CAV:
    - CB_12
  AI:
    - CB_12
  Ds575:
    - AS_16
  Ds595:
    - AS_16
  Ds2080:
    - AS_16
VOLCANIC:
  PGV:
    - Br_10
  PGA:
    - Br_10
  pSA:
    - Br_10
  CAV:
    - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  AI:
    - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  Ds575:
    - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  Ds595:
    - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
SUBDUCTION_SLAB:
  PGV:
    - Br_10 # These are only for shallow crustal in lieu of a more appropriate model
  PGA:
    - ZA_06
  pSA:
    - ZA_06
  CAV:
    - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  AI:
    - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  Ds575:
    - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  Ds595:
    - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
SUBDUCTION_INTERFACE:
  PGV:
    - Br_10 # These are only for shallow crustal in lieu of a more appropriate model
  PGA:
    - ZA_06
  pSA:
    - ZA_06
  CAV:
    - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  AI:
    - CB_12 # These are only for shallow crustal in lieu of a more appropriate model
  Ds575:
    - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
  Ds595:
    - AS_16 # These are only for shallow crustal in lieu of a more appropriate model
